### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by thejustsoul** [mjasny/vlc-youtubeDL#1]
Hello. How to use this addon? On `Windows 7 x64 with VLC 2.2.4 x86`.
I try to copy both .lua to `%appdata%\vlc\lua\extensions` (and ...`vlc\lua\playlist`) then start VLC and open URL with video (which support youtube-dl) and.. nothing.
I also tried to copy `youtube-dl.exe` to `VLC folder`, `lua\extensions`, `lua\playlist` and add to PATH.. Tried edit `youtube-dl.lua` and change full path to youtube-dl.exe and.. nothing.
Video not played. Maybe I missed something?
Please, step-by-step if possible.

**Comment by Mattze96** [comment]
it was programmed for linux.

you should only have to change it to youtube-dl.exe in the io.popen line. also include the json.lua file in your plugin directory.

**Comment by thejustsoul** [comment]
I change:
`  local file = assert(io.popen('youtube-dl -j '..url, 'r'))  --run youtube-dl in json mode`
to
 ` local file = assert(io.popen('youtube-dl.exe -j '..url, 'r'))  --run youtube-dl in json mode`
Video don't play.. Where to copy `youtube-dl.exe` for the video to start playing? Add to PATH, not work. Copy to extension folder, VLC folder, Windows\System32 (and SysWOW64) also.

**Comment by mjasny** [comment]
Usage instructions are now in the Readme
