### ISSUE TITLE
Decoding JSON fails with non-English LC_NUMERIC

### ISSUE THREAD

**Issue by jtojnar** [mjasny/vlc-youtubeDL#3]
Turns out VLC uses old and buggy dkjson version, I opened an [issue](https://trac.videolan.org/vlc/ticket/25280) against VLC.

If you encounter videos mysteriously not playing, try adding latest version of [dkjson](http://dkolf.de/src/dkjson-lua.fsl/home) to `~/.local/share/vlc/lua/modules/`.

**Comment by atagmester** [comment]
Adding `os.setlocale("C")` to the beginning of the script solves it....

**Comment by mjasny** [comment]
Super cool that you found the issue.

**Comment by jtojnar** [comment]
I would seriously advise against using that. [setlocale(3)](https://www.man7.org/linux/man-pages/man3/setlocale.3.html) is not thread-safe and, if `os.setlocale` is just a wrapper around the libc function, there is a [chance of it seriously fucking up VLC](https://en.cppreference.com/w/c/locale/setlocale#Notes).

In worst case, you might get random crashes – much harder to debug than explicit decode errors.

If you really want to fix it, just download latest version of dkjson until [code.videolan.org/videolan/vlc/-/merge_requests/3318](https://code.videolan.org/videolan/vlc/-/merge_requests/3318) is merged.
