### ISSUE TITLE
Some videos does not have subtiltes

### ISSUE THREAD

**Issue by soredake** [mjasny/vlc-youtubeDL#8]
For example https://www.crunchyroll.com/rezero-starting-life-in-another-world-/episode-42-a-journey-through-memories-801489

**Comment by mjasny** [comment]
Currently vlc lua extension doesn't support subtitle tracks, thus no subtitles can be displayed. (See: https://github.com/videolan/vlc/blob/master/modules/lua/libs/sd.c#L104) 

If someone knows has more information on this, please drop a message.
