### ISSUE TITLE
Some videos does not have sound

### ISSUE THREAD

**Issue by soredake** [mjasny/vlc-youtubeDL#9]
https://www.youtube.com/watch?v=YAVIZrs4HTc

**Comment by mjasny** [comment]
For me the video has sound, I did just:

```
vlc https://www.youtube.com/watch?v=YAVIZrs4HTc
```
You can try to use `vlc -vv` and search the output for errors. Another thing to try is to download the video through youtube-dl and check if the downloaded videofile has sound.

**Comment by d-air1** [comment]
I seem to have the same problem. What is happening however is that in some videos, the best quality video and the best quality audio are not always available together. Running vlc from the command line followed by the url like in your example will indeed result in a video with sound, but that video will usually be at a lower quality.

For example the output of:
youtube-dl -F affected_video_url

format code  extension  resolution note
249          webm       audio only tiny   50k , webm_dash container, opus @ 50k (48000Hz), 5.12MiB
250          webm       audio only tiny   65k , webm_dash container, opus @ 65k (48000Hz), 6.67MiB
251          webm       audio only tiny  123k , webm_dash container, opus @123k (48000Hz), 12.55MiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 13.11MiB
160          mp4        256x128    144p   29k , mp4_dash container, avc1.4d400c@  29k, 30fps, video only, 3.02MiB
278          webm       256x128    144p   57k , webm_dash container, vp9@  57k, 30fps, video only, 5.81MiB
133          mp4        426x214    240p   59k , mp4_dash container, avc1.4d400d@  59k, 30fps, video only, 6.06MiB
242          webm       426x214    240p   86k , webm_dash container, vp9@  86k, 30fps, video only, 8.76MiB
134          mp4        640x320    360p  100k , mp4_dash container, avc1.4d401e@ 100k, 30fps, video only, 10.15MiB
243          webm       640x320    360p  160k , webm_dash container, vp9@ 160k, 30fps, video only, 16.21MiB
135          mp4        854x428    480p  160k , mp4_dash container, avc1.4d401f@ 160k, 30fps, video only, 16.23MiB
244          webm       854x428    480p  278k , webm_dash container, vp9@ 278k, 30fps, video only, 28.21MiB
136          mp4        1280x640   720p  244k , mp4_dash container, avc1.4d401f@ 244k, 30fps, video only, 24.76MiB
247          webm       1280x640   720p  519k , webm_dash container, vp9@ 519k, 30fps, video only, 52.56MiB
137          mp4        1920x960   1080p  842k , mp4_dash container, avc1.640028@ 842k, 30fps, video only, 85.28MiB
248          webm       1920x960   1080p  936k , webm_dash container, vp9@ 936k, 30fps, video only, 94.78MiB
271          webm       2560x1280  1440p 2363k , webm_dash container, vp9@2363k, 30fps, video only, 239.23MiB
313          webm       3840x1920  2160p 7770k , webm_dash container, vp9@7770k, 30fps, video only, 786.60MiB
18           mp4        640x320    360p  359k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz), 36.34MiB
22           mp4        1280x640   720p  373k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)

Here you can see that the mp4 container marked as the "best" version here. Is only at 1280x640 when their is obviously higher quality video available in the output.

Another way of testing affected video url's is by running youtube-dl with the -g option like so:
youtube-dl -g video-url

This will return the true url of the video.
As you may notice, some videos return two urls. One for the best quality video and one for the best quality audio.

I attempted to resolve the situation by opening one network stream. Clicking the advanced options checkbox and then under the section where it says to open another file synchronously. I tried opening another network stream. However, vlc seems to only play one of them. Depending on which stream you opened first. It will play either the audio or the video. I know that mpv also uses youtube-dl to play youtube videos. It does not seem to be affected by this issue though. Perhaps their is something that they are doing that can help us here?

**Comment by soredake** [comment]
MPV script for youtube-dl is quite complex https://github.com/mpv-player/mpv/blob/master/player/lua/ytdl_hook.lua

I don't have interest in vlc anymore.
